### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sstarcher**
the repo could also be renamed

### CODE REVIEW

**Comment by majormoses** [comment]
I ran into the same issue as well, renaming repo is probably more of a pain than updating the documentation.

**Review by majormoses — APPROVED** [review]
LGTM

**Review by matthewdfuller — COMMENTED** [review]
Thanks - we'll rename the repo instead (quite an embarrassing typo!)

**Comment by majormoses** [comment]
> (quite an embarrassing typo!)

No worries we have all been there before.

**Comment by matthewdfuller** [comment]
Closing this now since we've renamed the repo. Thanks again!

**Pull request closed without merging**
